### ISSUE TITLE
Flatpaked apps don't respect system language

### ISSUE THREAD

**Issue by ryonakano** [elementary/flatpak-platform#38]
## What Happened

![Screenshot from 2021-05-04 11-09-14](https://user-images.githubusercontent.com/26003928/116953983-a1546a00-acc9-11eb-9629-9a31b8e55b9d.png)

*Flatpaked* elementary apps like Calculator and Screenshot don't respect system language; they are always shown in English regardless of the language used in the system entirely.

## Expected Behavior

*Flatpaked* elementary apps should also follows the system language.

## Steps to Reproduce

1. Set your system language to non-English language e.g. Japanese
2. Relogin
3. Run *flatpaked* Calculator or Screenshot

### Logs

N/A

## Platform Information

- elementary OS 6 Beta with fully updated

**Comment by Marukesu** [comment]
I believe that the problem here is that flatpak only download the locale in use, so when you change the locale you need to run `flatpak update` or re-install the locale with `--subpath`, for example:
```
flatpak install --re-install --subpath=en --subpath=ja io.elementary.Platform.Locale io.elementary.calculator.Locale
```
will re-install both locales with english and japanese support.

**Comment by cassidyjames** [comment]
We should probably run `flatpak update` or something when changing your locale, then, right? But I guess since these were originally installed when the OS was being built, we should `flatpak update` when you first log in? I guess this will be resolved if we enable auto updates, too…

Hm. Lots to think about.

**Comment by hanaral** [comment]
It's probably a safe bet to install the other locales while providing the same 'installation required' banner in the locale plug as usual. I'll always point back to the way that component downloads are managed in the AppCenter, where OS stuff that are critical to operation are in the same list as app updates.
- Maybe there should be some kind of special undissmissable notification type that can show component installs? (like android has in the notif. shade)

**Comment by Marukesu** [comment]
> We should probably run `flatpak update` or something when changing your locale, then, right?

yes, but `flatpak update` will ending updating all the flatpaks installed, not only the locales, maybe using libflatpak and selecting only to update the `org.app.App.Locale` extensions, but i wonder if there's a update on the app too it's gonna break.
we can also install all the locales.

> But I guess since these were originally installed when the OS was being built, we should `flatpak update` when you first log in?

Looking at elementary/browser#14, it's seem that the problem is only if the locale is changed after the install.

**Comment by ryonakano** [comment]
OK, [this fix](https://github.com/elementary/screenshot/pull/214) seems to resolve the issue.
